# Generated by Django 3.2.13 on 2023-02-16 00:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20230215_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='ddd_phone',
            field=models.CharField(max_length=2, null=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
